stages:
    - build_container
    - build_signal_desktop
      #- build_ringrtc

# Broken: gitlab CI runners don't support QEMU-binfmt
build_container:
    stage: build_container
    image: docker:latest
    services:
        - docker:dind
    script:
        - apt update && apt install qemu-user-static
        - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
        - docker build -t ${CI_REGISTRY}/undef1/signal-desktop-builder:latest -f Dockerfile .
        - docker push ${CI_REGISTRY}/undef1/signal-desktop-builder

build_signal_desktop:
    stage: build_signal_desktop
    image: ${CI_REGISTRY}/undef1/signal-desktop-builder:latest
    script:
        - /signal-buildscript.sh
